export const sampleData = {
  general: {
    basicSalary: 0,
    hra: 0,
    medicalAllowance: 0,
    conveyanceAllowance: 0,
    specialAllowance: 0,
    otherAllowance: 0,
    lta: 0,
    mealAllowance: 0,
    npsContribution: 0,
    childrenEducationAllowance: 0,
    hostelAllowance: 0,
    washingAllowance: 0,
    uniformAllowance: 0,
    otherReimbursements: 0,
    otherAllowances: 0,
  },
  monthlySalaryDetails: {
    grossAnnualSalaryOld: 0,
    grossAnnualSalaryNew: 0,
  },
  taxability: {
    oldRegime: {
      grossAnnualSalary: 0,
      nonTaxableAllowances: 0,
      professionalTax: 0,
      standardDeduction: 0,
      hraExemption: 0,
      ltaExemption: 0,
      lossFromHouse: 0,
      incomeFromHouse: 0,
      incomeFromOther: 0,
    },
    newRegime: {
      grossAnnualSalary: 0,
      nonTaxableAllowances: 0,
      professionalTax: 0,
      standardDeduction: 0,
      hraExemption: 0,
      ltaExemption: 0,
      lossFromHouse: 0,
      incomeFromHouse: 0,
      incomeFromOther: 0,
    },
  },
  investments: {
    currentEmployerPf: 0,
    previousEmployerPf: 0,
    vpf: 0,
    lip: 0,
    ppf: 0,
    cef: 0,
    pensionFunds: 0,
    fd: 0,
    ulip: 0,
    hlp: 0,
    elss: 0,
    nsc: 0,
    stampDuty: 0,
    otherInvestments: 0,
    totalInvestments: 0,
  },
  taxableIncome: {
    oldRegime: {
      incomeTax: 0,
      rebate87a: 0,
      balanceTax: 0,
      surcharge: 0,
      totalTax: 0,
      eduCess: 0,
      netAnnualTax: 0,
      taxSavings: 0,
    },
    newRegime: {
      incomeTax: 0,
      rebate87a: 0,
      balanceTax: 0,
      surcharge: 0,
      totalTax: 0,
      eduCess: 0,
      netAnnualTax: 0,
      taxSavings: 0,
    },
  },
  form16Details: {
    employeeName: "",
    employeeNo: "",
    pan: "",
    designation: "",
    financialYear: "",
    assessmentYear: "",
    form16Enclosed: "",
    form12BAEnclosed: "",
    taxableIncome: "",
    tax: "",
    signatureName: "",
    signatureDate: "",
  },
};
